owner: poldracklab
repo: uptime

sites:
  - name: OpenfMRI
    url: https://openfmri.org
  - name: Cognitive Atlas
    url: https://cognitiveatlas.org
assignees:
  - rwblair
  - effigies

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Poldrack Lab Web Dashboard
  introTitle: "Poldrack Lab Web Dashboard"
  introMessage: This status page tracks the uptime status of projects maintained by the [Poldrack Lab](https://poldracklab.stanford.edu/). Built using the open [**Upptime**](https://github.com/upptime/upptime) app on [GitHub](https://github.com).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
